apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
        - name: iris-container
          image: l00187454/iris-flask-api:latest
          ports:
            - containerPort: 5000
